# Generated by Django 5.2.8 on 2025-11-26 07:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommender", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="id",
        ),
        migrations.AlterField(
            model_name="movie",
            name="genres",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="movie",
            name="movie_id",
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name="rating",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
